## external control via relay

#type: relay
#maxPower: 4200 # limit loadpoints to 4.2 kW total
#limit: # limit signal, plugin
#  source: mqtt
#  topic: hems/limit/status # 0/false = normal, 1/true = limit active

## external control via EEBus

#type: eebus # general EEBus setup (cert gen) required
#ski: "1234-5678-90AB-CDEF" # SKI of control box (grid operator)

## external loadpoint control via Tibber Grid Reward

#type: tibbergridreward
#username: your@email.com
#password: "your-tibber-password"
#loadpoint: 1           # loadpoint index (1-based)
#refresh: 5m            # lease renewal interval
#homeId: "your-home-id" # optional: only required for multiple homes